FROM debian:buster-slim

RUN groupadd -g 999 mysql
RUN useradd -u 999 -r -g 999 -s /sbin/nologin \
    -c "Default Application User" mysql

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https ca-certificates unzip pigz wget gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        default-mysql-client \
    && rm -rf /var/lib/apt/lists/*
    
RUN echo 'deb https://repo.percona.com/apt buster main' > /etc/apt/sources.list.d/percona.list

RUN apt-get update

RUN apt-get install -y --no-install-recommends percona-toolkit
RUN rm -rf /var/lib/apt/lists/*

RUN apt-get install -y --no-install-recommends percona-xtrabackup-24
RUN rm -rf /var/lib/apt/lists/*

