FROM debian:buster-slim

RUN groupadd -g 999 mysql
RUN useradd -u 999 -r -g 999 -s /sbin/nologin \
    -c "Default Application User" mysql

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https ca-certificates unzip pigz wget gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN echo 'deb https://repo.percona.com/apt buster main' > /etc/apt/sources.list.d/percona.list

ARG XTRABACKUP_PKG=percona-xtrabackup-24
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        percona-toolkit ${XTRABACKUP_PKG} unzip default-mysql-client \
    && rm -rf /var/lib/apt/lists/*

